#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100 with FIZZBUZZ
for i in {1..100}
do
	if  (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif  (( i % 5 == 0 )) &&  (( i % 3 != 0 ))
	then
		echo "Buzz"
	elif  (( i % 3 == 0 )) &&  (( i % 5 != 0 ))
	then
		echo "Fizz"
	else
		echo $i
	fi
done
