#!/usr/bin/env bash
#loops from 1 to 10. 4 displays bad luck, 8 displays good luck
while [[ $x -le 9 ]]
do
	if [[ $x -eq 3 ]]
	then
	    echo "bad luck"
	elif [[ $x -eq 7 ]]
	then
	    echo "good luck"
	else
	    echo "Holberton School"
	fi
	x=$(( x + 1 ))
done
